/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: SignalModule.idl
  Source: SignalModule.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_SIGNALMODULE_HPP
#define DDSCXX_SIGNALMODULE_HPP

#include <cstdint>
#include <string>

namespace SignalModule
{
class LocationSignal
{
private:
    bool flag_ = false;

public:
    LocationSignal() = default;
    explicit LocationSignal(bool flag) : flag_(flag) {}

    bool flag() const { return flag_; }
    bool& flag() { return flag_; }
    void flag(bool val) { flag_ = val; }

    bool operator==(const LocationSignal& other) const
    {
        return flag_ == other.flag_;
    }
    bool operator!=(const LocationSignal& other) const
    {
        return !(*this == other);
    }
};
}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::SignalModule::LocationSignal>::getTypeName()
{
    return "SignalModule::LocationSignal";
}

template <> constexpr bool TopicTraits<::SignalModule::LocationSignal>::isSelfContained()
{
    return false;
}

template <> constexpr bool TopicTraits<::SignalModule::LocationSignal>::isKeyless()
{
    return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::SignalModule::LocationSignal>::type_map_blob_sz() { return 64; }
template<> constexpr unsigned int TopicTraits<::SignalModule::LocationSignal>::type_info_blob_sz() { return 16; }
template<> inline const uint8_t * TopicTraits<::SignalModule::LocationSignal>::type_map_blob() {
    static const uint8_t blob[] = {
        0x10, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
        0xf1, 0x79, 0xbc, 0x4c, 0x32, 0x6b, 0x24, 0xd2,
        0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
        0x66, 0x6c, 0x61, 0x67, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    };
    return blob;
}
template<> inline const uint8_t * TopicTraits<::SignalModule::LocationSignal>::type_info_blob() {
    static const uint8_t blob[] = {
        0x10, 0x00, 0x00, 0x00, 0x01, 0x10, 0x00, 0x40,
        0x10, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
    };
    return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::SignalModule::LocationSignal>
{
    static std::string value()
    {
        return org::eclipse::cyclonedds::topic::TopicTraits<::SignalModule::LocationSignal>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::SignalModule::LocationSignal)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::SignalModule::LocationSignal>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::SignalModule::LocationSignal& instance, entity_properties_t *props) {
    (void)instance;
    if (!streamer.start_struct(*props))
        return false;
    auto prop = streamer.first_entity(props);
    while (prop) {
        switch (prop->m_id) {
            case 0:
                if (!streamer.start_member(*prop))
                    return false;
                if (!write(streamer, instance.flag()))
                    return false;
                if (!streamer.finish_member(*prop))
                    return false;
                break;
        }
        prop = streamer.next_entity(prop);
    }
    return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::SignalModule::LocationSignal& instance, bool as_key) {
    auto &props = get_type_props<::SignalModule::LocationSignal>();
    str.set_mode(cdr_stream::stream_mode::write, as_key);
    return write(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::SignalModule::LocationSignal& instance, entity_properties_t *props) {
    (void)instance;
    if (!streamer.start_struct(*props))
        return false;
    auto prop = streamer.first_entity(props);
    while (prop) {
        switch (prop->m_id) {
            case 0:
                if (!streamer.start_member(*prop))
                    return false;
                if (!read(streamer, instance.flag()))
                    return false;
                if (!streamer.finish_member(*prop))
                    return false;
                break;
        }
        prop = streamer.next_entity(prop);
    }
    return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::SignalModule::LocationSignal& instance, bool as_key) {
    auto &props = get_type_props<::SignalModule::LocationSignal>();
    str.set_mode(cdr_stream::stream_mode::read, as_key);
    return read(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::SignalModule::LocationSignal& instance, entity_properties_t *props) {
    (void)instance;
    if (!streamer.start_struct(*props))
        return false;
    auto prop = streamer.first_entity(props);
    while (prop) {
        switch (prop->m_id) {
            case 0:
                if (!streamer.start_member(*prop))
                    return false;
                if (!move(streamer, instance.flag()))
                    return false;
                if (!streamer.finish_member(*prop))
                    return false;
                break;
        }
        prop = streamer.next_entity(prop);
    }
    return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::SignalModule::LocationSignal& instance, bool as_key) {
    auto &props = get_type_props<::SignalModule::LocationSignal>();
    str.set_mode(cdr_stream::stream_mode::move, as_key);
    return move(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::SignalModule::LocationSignal& instance, entity_properties_t *props) {
    (void)instance;
    if (!streamer.start_struct(*props))
        return false;
    auto prop = streamer.first_entity(props);
    while (prop) {
        switch (prop->m_id) {
            case 0:
                if (!streamer.start_member(*prop))
                    return false;
                if (!max(streamer, instance.flag()))
                    return false;
                if (!streamer.finish_member(*prop))
                    return false;
                break;
        }
        prop = streamer.next_entity(prop);
    }
    return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::SignalModule::LocationSignal& instance, bool as_key) {
    auto &props = get_type_props<::SignalModule::LocationSignal>();
    str.set_mode(cdr_stream::stream_mode::max, as_key);
    return max(str, instance, props.data());
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_SIGNALMODULE_HPP
