# 舵机控制配置文件
# 设备配置
device_port: "/dev/ttyUSB0"
baudrate: 1000000

# 舵机参数
servo0_calibration: 1440
servo1_calibration: 2348

# 关节限制
joint0: [-50, 50]
joint1: [-20, 85]

# 方向设置
direction: [1, -1]

# 控制参数
dt: 0.015
has_calibrate: 0 